discord:
  roleResolveEnabled: false
  token: ${DISCORD_BOT_TOKEN}

mongo:
  connString: ${MONGO_CONNECTION_STRING}

management:
  endpoints:
    web:
      exposure:
        include: health
    health:
      enabled: true